/**
 * エージェント help ツール用ガイド本文 (S10a31c-2 / ADR-0014)。
 *
 * ADR-0014 決定: DQL / テンプレート / DataView 等の詳細な使い方は base システムプロンプトに
 * 常駐させず、help ツールがトピック指定で必要時に供給する。
 *
 * ガイド本文は Loamium 同梱・バージョン管理 (このコード内マップが正本)。
 * トピックは小文字 ASCII キーで固定する。未知/未指定トピックはエラーにせず
 * 利用可能トピック一覧を返す (AC-S10a31c-2-1)。
 */

/**
 * [ADR-0014] GET /api/events (SSE) はエージェントツールを持たない。
 * 理由: SSE は UI が受動的に購読するプッシュインフラであり、
 * エージェントが直接操作する対象ではない (Sd5c9f4-3 設計判断)。
 */

/**
 * トピック名 → ガイド本文。
 * キーは正規化済み (小文字) を前提とする。resolveHelpTopic() で正規化する。
 */
export const AGENT_HELP_TOPICS: Record<string, string> = {
  dql: [
    '# DQL (Loamium Query Language)',
    '',
    'query ツールで実行する簡易クエリ言語です。3 種のクエリ形式があります。',
    '',
    '- `LIST` — 条件に一致するノートを一覧します。例: `LIST FROM #project`',
    '- `TABLE <field>, ...` — 指定フィールドを表形式で返します。例: `TABLE title, tags WHERE folder = "project"`',
    '- `TASK` — ノート内のタスク (チェックボックス) を集計します。例: `TASK WHERE status = "open"`',
    '',
    '句:',
    '- `FROM #tag` — 指定タグを持つノートに絞り込みます。',
    '- `WHERE <field> = "value"` — フィールド値で絞り込みます (frontmatter のキーや folder 等)。',
    '- `SORT <field> [ASC|DESC]` — 並び替えます。',
    '',
    'まず小さなクエリで試し、件数を確認してから条件を足していくのが確実です。',
  ].join('\n'),

  template: [
    '# テンプレート (一覧・テンプレートからのノート作成)',
    '',
    'よく作るノートの雛形です。テンプレートはピュア Markdown で書かれ、',
    '変数を埋めて新規ノートを作成します。関連ツールは `templates_list` と',
    '`template_instantiate` の 2 つで、いずれも REST と同一のテンプレートサービス層',
    '(templates-service.ts) を経由します。',
    '',
    '## templates_list (一覧, 読み取り)',
    '',
    '- 入力: なし。',
    '- 出力: 定義済みテンプレートの一覧。各行に name (instantiate に使う識別子)・',
    '  説明・保存先パターン・必須変数を表示します。壊れたテンプレートはスキップされます。',
    '- 経由サービス: listTemplates (system/templates/ を優先, fallback: templates/)。',
    '',
    '## template_instantiate (ノート作成, 書き込み)',
    '',
    '- 入力パラメータ:',
    '  - `name` — 適用するテンプレート名 (templates_list で確認)。',
    '  - `vars` — 変数名 → 値のマップ (省略可)。テンプレート本文中の可変部分を埋めます。',
    '  - `date` — `{{date}}` の基準日 (YYYY-MM-DD、省略時は今日)。',
    '- 出力: 生成されたノートのパス。必須変数が不足していれば missing 一覧を返します。',
    '- 経由サービス: instantiateTemplate。保存先が既存ノートと衝突する場合は連番で回避します。',
    '',
    '使用例 — 日報テンプレートに変数と基準日を渡してノートを作る:',
    '',
    '- `template_instantiate` に `name: "daily"`,',
    '  `vars: { "title": "定例MTG", "author": "自分" }`, `date: "2026-07-16"` を渡す。',
    '- テンプレート本文の `{{title}}` / `{{author}}` / `{{date}}` が埋められ、',
    '  保存先パターンに従って新規ノートが作られます。',
    '',
    '注意点:',
    '',
    '- 結果ノートはピュア Markdown です。テンプレート記法は解決後に残りません。',
    '- テンプレートに独自記法やブロック ID を持ち込まないでください (ピュア Markdown を維持)。',
    '- 生成 (書き込み) には権限が必要です。読み取り専用の権限セットでは',
    '  template_instantiate は利用できず、templates_list のみ使えます。',
    '- system 領域や機密領域への保存はサービス層のパス検証・deny により拒否されます。',
    '',
    '## template_write (テンプレート authoring, 書き込み)',
    '',
    'テンプレートノート (templates/<name>.md) 自体を作成・更新します。',
    'note-service を経由し、ピュア Markdown の YAML フロントマター (type: template を自動付与) を書きます。',
    '',
    '- 入力パラメータ:',
    '  - `name` — テンプレート名 (templates/<name>.md に保存)。',
    '  - `body` — テンプレート本文 (ピュア Markdown)。',
    '  - `frontmatter` — 追加の frontmatter キー→スカラー値マップ (任意)。',
    '  - `overwrite` — true なら既存テンプレートを上書き (既定 false: 既存はエラー)。',
    '- 既定 (overwrite 省略/false) では既存テンプレートを上書きしません。更新する場合は overwrite:true を指定します。',
    '',
    '## template_delete (テンプレート削除, 書き込み)',
    '',
    '- 入力: `name` (削除するテンプレート名。templates/<name>.md を削除)。',
    '- **この操作は不可逆です**。存在しない name はエラーにせず「削除対象なし」を返します (冪等)。',
    '',
    '注意点 (authoring 系):',
    '',
    '- template_write / template_delete は template_write ケーパビリティで広告され、full 権限モードでのみ使えます。',
    '- vault 脱出 / 隠しセグメント / 機密領域 (deny) への書き込み・削除は拒否されます。',
    '- テンプレートに独自記法・ブロック ID を持ち込まないでください (ピュア Markdown を維持)。',
  ].join('\n'),

  smartfolder: [
    '# スマートフォルダ (ビュー定義)',
    '',
    'スマートフォルダは、条件に一致するノートをまとめて表示する保存済みビュー定義です。',
    '2 種類あります: query (DQL で動的に一致させる) と pin (特定ノート/フォルダ配下を固定)。',
    '関連ツールは 4 つで、いずれも REST と同一のサービス層 (smart-folders-service.ts /',
    'system-store.ts) を経由します。定義は system/smart-folders/{id}.yaml に保存されます。',
    '',
    '## smartfolders_list (一覧, 読み取り)',
    '',
    '- 入力: なし。',
    '- 出力: 定義済みスマートフォルダの一覧。各行に id・name・kind (query|pin)・',
    '  DQL または pin パスを表示します。',
    '',
    '## smartfolder_notes (解決, 読み取り)',
    '',
    '- 入力パラメータ: `id` — 解決するスマートフォルダ id (smartfolders_list で確認)。',
    '- 出力: そのビューに含まれるノートのパス一覧 ([[リンク]] 形式)。',
    '  query は DQL を実行し、pin はノート/フォルダ配下を解決します。',
    '- 機密領域のノートは一覧に含まれません (deny 除外ビュー経由)。',
    '',
    '## smartfolder_write (作成/更新, 書き込み)',
    '',
    '- 入力パラメータ:',
    '  - `id` — スマートフォルダ id (ファイル名。既存なら上書き)。',
    '  - `name` — 表示名。',
    '  - `dql` — DQL クエリ (LIST / TABLE / TASK)。保存前に構文検証されます。',
    '  - `icon` — アイコン名 (任意)。',
    '- 出力: 作成/更新したことと id。DQL 構文が不正なら保存されずエラーを返します。',
    '- 経由サービス: serializeSmartFolderYaml + writeSystemSmartFolder。',
    '',
    '使用例 — DQL クエリでプロジェクトノートを集めるビューを作る:',
    '',
    '- `smartfolder_write` に `id: "projects"`, `name: "進行中プロジェクト"`,',
    '  `dql: "LIST FROM #project WHERE status = \\"open\\""` を渡す。',
    '- 以後 `smartfolder_notes` に `id: "projects"` を渡すと一致ノートを解決できます。',
    '- DQL の文法は help トピック `dql` を参照してください。',
    '',
    '## smartfolder_delete (削除, 書き込み)',
    '',
    '- 入力パラメータ: `id` — 削除するスマートフォルダ id。',
    '- 出力: 削除結果。存在しない id はエラーにせず「削除対象なし」を返します。',
    '',
    '注意点:',
    '',
    '- 作成/更新/削除 (書き込み) には権限が必要です。読み取り専用の権限セットでは',
    '  smartfolders_list / smartfolder_notes のみ利用できます。',
    '- id のパスは正規化・検証されます (`..` 脱出や機密領域への書き込みは拒否)。',
    '- ビュー定義は Loamium が管理する YAML です。手書きの独自記法を持ち込まず、',
    '  必ずこれらのツール経由で操作してください。',
  ].join('\n'),

  command: [
    '# スマートコマンド (定型操作の実行・authoring)',
    '',
    'スマートコマンドは、複数ステップの定型操作 (ノート作成・追記・プロパティ設定・',
    'エージェント実行など) を 1 つの id にまとめた保存済み手順です。関連ツールは 4 つで、',
    'いずれも REST と同一のサービス層 (commands-service.ts / system-store.ts) を経由します。',
    '定義は system/commands/*.yaml (fallback: commands/*.yaml) に置かれます。',
    '',
    '## commands_list (一覧, 読み取り)',
    '',
    '- 入力: なし。',
    '- 出力: 定義済みコマンドの一覧。各行に id (run に使う識別子)・表示名・説明・',
    '  必須 param を表示します。壊れた定義も無効として一覧に含まれます。',
    '',
    '## command_run (実行, 書き込み)',
    '',
    '- 入力パラメータ:',
    '  - `id` — 実行するコマンド id (commands_list で確認)。',
    '  - `params` — パラメータ名 → 値のマップ (省略可)。ステップ内で参照されます。',
    '- 出力: 各ステップの実行結果 (OK / スキップ / 失敗)。',
    '  必須 param 不足や最初の失敗ステップで停止します (ロールバックなし = fail-stop)。',
    '- 経由サービス: runCommand (REST の run と同一のステップ実行エンジン)。',
    '',
    '使用例 — params を渡して定型ノートを作るコマンドを実行する:',
    '',
    '- まず `commands_list` で id と必須 param を確認する。',
    '- 次に `command_run` に `id: "new-meeting"`,',
    '  `params: { "topic": "設計レビュー", "attendees": "3" }` を渡す。',
    '- コマンド定義のステップが順に実行され、各ステップの結果が返ります。',
    '',
    '## command_write (作成/更新, 書き込み)',
    '',
    '- 入力パラメータ:',
    '  - `name` — コマンド id (ファイル stem。例: "new-meeting")。既存なら上書き。',
    '  - `source` — コマンド YAML ファイル全体のテキスト (下記 DSL スキーマに従う)。',
    '- 出力: 作成/更新の結果。保存前に YAML を検証し、不正なら保存せずエラーを返します',
    '  (壊れた定義は書き込まれません)。',
    '- 保存先: system/commands/{name}.yaml (純 YAML, UTF-8/LF)。',
    '',
    '## command_delete (削除, 書き込み)',
    '',
    '- 入力パラメータ: `name` — 削除するコマンド id。',
    '- 出力: 削除結果。存在しない name はエラーにせず「削除対象なし」を返します。',
    '',
    '## コマンド YAML の DSL スキーマ (command_write の source)',
    '',
    'ファイル全体がトップレベルのコマンドオブジェクトです。ラッパーキーは不要です。',
    '',
    '```yaml',
    'name: 会議メモを作る          # 省略可。パレット表示名 (省略時はファイル名)',
    'description: 会議の定型ノートを作成する  # 省略可。説明',
    'params:                       # 省略可。実行前フォームの入力定義',
    '  - name: topic               # 必須。{{topic}} で参照',
    '    label: 議題               # 省略可。表示ラベル',
    '    required: true            # 省略可。true なら未入力で run は失敗',
    '    type: string              # 省略可。string|text|date|select|note|boolean|number',
    '    default: ""               # 省略可。既定値',
    '    # type: select のときは options (非空配列) が必須',
    '    # options: [A, B, C]',
    'steps:                        # 必須。1 個以上のステップを順次実行',
    '  - kind: note-create',
    '    target: "meetings/{{topic}}"',
    '    content: "# {{topic}}\\n\\n## アジェンダ\\n"',
    '    open: true',
    '```',
    '',
    'params の値は `{{name}}` でステップの文字列フィールド (target/content/old/new/',
    'prompt/set の値など) に展開されます。日付は `{{date:YYYY-MM-DD}}` 等も使えます。',
    '',
    '### ステップ種 (kind) と必須フィールド',
    '',
    '各ステップは `kind` で判別します。共通の任意フィールド: `when` / `when-not`',
    '(値が truthy/falsey かで実行・スキップ。falsey は "" / "false" / "0")、`open`',
    '(true で対象を開く。note-patch/prop-set を除く)。',
    '',
    '- `journal-append` — ジャーナルへ追記。',
    '  必須: `content`。任意: `date` (省略時は今日), `section` (見出し配下末尾),',
    '  `position` (bottom|top|section)。',
    '- `note-append` — 既存ノートへ追記。',
    '  必須: `target`, `content`。任意: `section`, `create` (true で無ければ新規作成),',
    '  `position` (bottom|top|section)。',
    '- `note-create` — 新規ノート作成 (衝突時は連番サフィックス)。',
    '  必須: `target`, `content`。',
    '- `template-instantiate` — 既存テンプレートでノート生成。',
    '  必須: `template` (テンプレート id)。任意: `vars` (変数名→値マップ)。',
    '- `prop-set` — frontmatter プロパティを upsert/unset。',
    '  必須: `target`。任意: `set` (キー→値マップ, string|number|boolean),',
    '  `unset` (削除キー名の配列)。append-only モードでは実行不可。',
    '- `note-patch` — ノート内テキストを置換。',
    '  必須: `target`, `old`, `new`。非マッチ/複数マッチは失敗。append-only 不可。',
    '- `agent-run` — 賢い処理を Pi エージェントへ委譲 (書き込みはエージェントが監査済み',
    '  ツールで行う)。必須: `prompt` (非空)。任意: `permissions`, `maxTurns` (1..50),',
    '  `timeoutSec` (10..600)。append-only モードでは実行不可。',
    '',
    '  agent-run の権限 (least-privilege): `permissions` 未指定なら **既定 read-only**',
    '  = 書き込み不可 (agent.json の権限は継承しない)。プリセット: read-only=[read] /',
    '  notes-rw=[read, journal_append, note_create, note_edit] / full=全ケーパビリティ。',
    '  web 検索や特定ツールが要るなら個別ケーパビリティ配列で明示付与する',
    '  (例 `permissions: [read, web, note_create]`)。実効権限はサーバーの',
    '  LOAMIUM_MODE でさらにクランプされる (ADR-0015)。',
    '',
    '### 例: 複数ステップ + 条件付き',
    '',
    '```yaml',
    'name: タスク完了',
    'params:',
    '  - name: note',
    '    type: note',
    '    required: true',
    '  - name: notify',
    '    type: boolean',
    'steps:',
    '  - kind: prop-set',
    '    target: "{{note}}"',
    '    set:',
    '      status: done',
    '  - kind: journal-append',
    '    when: "{{notify}}"          # notify が truthy のときだけ実行',
    '    content: "- 完了: [[{{note}}]]"',
    '```',
    '',
    '注意点:',
    '',
    '- 実行・作成・更新・削除 (書き込み) には権限が必要です。読み取り専用の権限セットでは',
    '  commands_list のみ利用でき、command_run / command_write / command_delete は利用できません。',
    '- append-only モードでは prop-set / note-patch / agent-run を含むコマンドの実行は拒否されます。',
    '- 各ステップの保存先パス検証・機密領域 deny はサービス層が REST と同一に処理します。',
    '- name (id) のパスは正規化・検証されます (`..` 脱出や機密領域への書き込みは拒否)。',
    '- コマンド定義は Loamium が管理する純 YAML です。ブロック ID や独自記法をファイルに',
    '  書き込まず、上記 DSL スキーマに従って、必ずこれらのツール経由で操作してください。',
  ].join('\n'),

  dataview: [
    '# DataView 風の集計',
    '',
    'ノート横断の集計・一覧は DQL (query ツール) で行います。',
    'Obsidian の DataView プラグインに相当する用途は、Loamium では DQL に集約されています。',
    '',
    '- 動的一覧が欲しいときは query ツールで `LIST` / `TABLE` を実行します。',
    '- 集計結果をノートに残したい場合は、query の結果を Markdown 表や箇条書きとして書き出します。',
    '- 詳細な文法は help トピック `dql` を参照してください。',
  ].join('\n'),

  wikilink: [
    '# [[ウィキリンク]]',
    '',
    'ノート間の参照は `[[ノート名]]` 記法で表します。',
    '',
    '- `[[design]]` のように拡張子なしのパス/タイトルで参照します。',
    '- 表示名を変えたいときは `[[design|設計メモ]]` と書きます。',
    '- backlinks ツールで、あるノートへの参照元 (バックリンク) 一覧を取得できます。',
    '- 出典を示すときは必ずこの [[リンク]] 記法を使ってください。',
  ].join('\n'),

  journal: [
    '# ジャーナル (日次ノート)',
    '',
    '日付ごとのノートです。ファイル名は `YYYY-MM-DD` 形式の日付を基準にします。',
    '',
    '- 「今日」「昨日」などの相対日付は、実際の日付に解決してから参照します。',
    '- ジャーナルもピュア Markdown です。追記は既存本文を壊さないよう末尾に足すのが基本です。',
    '- 日付に紐づくメモやタスクをまとめる場所として使います。',
  ].join('\n'),

  frontmatter: [
    '# フロントマター (YAML メタデータ)',
    '',
    'ノート先頭の `---` で囲まれた YAML ブロックにメタデータを書きます。',
    '',
    '- 例: `title`, `tags`, `date` などのキーを持てます。',
    '- frontmatter のキーは DQL の `WHERE` / `TABLE` で参照できます。',
    '- 既存の frontmatter を編集するときは YAML 構文を壊さないよう注意してください。',
    '',
    '## note_property (プロパティ/タグ編集, 書き込み)',
    '',
    'frontmatter のプロパティを安全に編集する専用ツールです。',
    'POST /api/notes/{path}/properties と同一のコア (applyPropSet) を経由し、',
    '既存ノートの frontmatter を直接書き換えます (本文は保持)。',
    '',
    '- 入力パラメータ:',
    '  - `path` — 対象の既存ノート (vault 相対パス)。',
    '  - `set` — 追加・更新するキー→スカラー値 (string/number/boolean/null) のマップ (upsert)。',
    '  - `unset` — 削除するプロパティキー名の配列。',
    '- **tags もこのツールで編集します**。例: `set: { "tags": "project" }` で tags プロパティを設定、',
    '  `unset: ["tags"]` で削除します。tags は特別扱いせず、frontmatter の 1 プロパティとして扱います。',
    '- 値はスカラーのみです。配列・ネストしたオブジェクトは安全な round-trip を保証できないため受け付けません。',
    '- frontmatter が安全に解析できない (壊れた YAML / アンカー / 重複キー等) 場合、または',
    '  直列化した結果を再解析できない場合は、ファイルを一切変更せずエラーを返します (データ安全性)。',
    '- 編集 (書き込み) には note_edit 権限が必要です (note_property は note_edit ケーパビリティに畳まれます)。',
  ].join('\n'),

  note: [
    '# ノートの作成・編集・削除 (書き込みツール)',
    '',
    'ノート本体を操作する書き込みツール群です。いずれも REST と同一のサービス層',
    '(note-service.ts / applyPropSet) を経由し、ピュア Markdown・パス正規化・監査ログを継承します。',
    '',
    '## note_create (新規作成, 書き込み)',
    '',
    '- 入力: `path` (vault 相対) と `content` (ピュア Markdown)。',
    '- 既存パスには作成しません (上書きしない)。既存を書き換えたいときは note_edit を使います。',
    '',
    '## note_edit (部分置換, 書き込み)',
    '',
    '- 入力: `path`, `old` (ノート内で一意な既存テキスト), `new` (置換後)。',
    '- old が 0 箇所 / 複数箇所 (曖昧) のときはエラーで、ファイルを変更しません (非破壊 patch)。',
    '',
    '## note_property (プロパティ/タグ編集, 書き込み)',
    '',
    '- frontmatter プロパティ (tags を含む) を set/unset で編集します。詳細は help トピック `frontmatter`。',
    '',
    '## note_move (リネーム/移動, 書き込み)',
    '',
    '- 入力: `from` (移動元 vault 相対パス), `to` (移動先 vault 相対パス)。',
    '- POST /api/notes/{path}/rename と同一のコア (renameNote) を経由し、vault 全体の',
    '  [[旧名]] リンクを新パスへ**一括追従**します (自己リンクも追従。曖昧リンクは触りません)。',
    '- 移動先が既に存在する場合はエラー (上書きしません)。from が存在しない場合もエラー。',
    '- from / to どちらかが機密領域 (deny) / vault 脱出のときは拒否されます。',
    '- 編集系のため note_edit 権限で広告されます (note_property と同じケーパビリティに畳まれます)。',
    '',
    '## note_convert_list (リストタイプ変換, 書き込み)',
    '',
    '- 入力: `path` (対象ノート), `target` ("bullet" = 箇条書き `- ` / "ordered" = 番号付き `1. `),',
    '  任意で `fromLine` / `toLine` (1-indexed の変換対象行範囲・両端含む。省略時はノート全体のリスト行)。',
    '- UI の Ctrl+Shift+8 (箇条書き) / Ctrl+Shift+7 (番号付き) と**同じ共有純関数** (convertListLines) を使い、',
    '  ネストのインデント・子項目・チェックボックス (`- [ ]`) を保持したままマーカーだけを書き換えます。',
    '- 番号付きへの変換時は CommonMark のネスト規則で採番します (各階層 1 から連番、子リストは 1 から再開)。',
    '- チェックボックスは温存されます: `- [ ] task` → ordered で `1. [ ] task` (bullet へ戻せば復帰・round-trip 可)。',
    '- 使用例: `{ "path": "todo", "target": "ordered" }` (ノート全体を番号付きへ) /',
    '  `{ "path": "todo", "target": "bullet", "fromLine": 3, "toLine": 6 }` (3–6 行目を箇条書きへ)。',
    '- 書き込みは note-service のフル置換層 (REST PUT と同一) を経由し `op: "agent.note_convert_list"` で監査記録されます。',
    '- 編集系のため note_edit 権限で広告されます (note_property / note_move / task_set_fields と同じケーパビリティ)。',
    '- 変換対象行にリスト行が無い / 既に目的タイプの場合は「変換なし」を返しファイルを変更しません。',
    '',
    '## note_delete (削除, 書き込み)',
    '',
    '- 入力: `path` (削除する vault 相対パス)。',
    '- **この操作は不可逆です** — ファイルを削除します。vault は Git 管理前提で、復旧は git 履歴に依存します。',
    '  削除前に本当に不要か確認してください。',
    '- 存在しない path はエラーにせず「削除対象なし」を返します (冪等)。',
    '- note_delete は破壊的なため独立した note_delete 権限が必要で、full 権限モードでのみ広告されます。',
    '',
    '共通の注意点:',
    '',
    '- vault 外への脱出 (`../`) / 隠しセグメント (`.loamium` 等) / 機密領域 (privacy deny) は',
    '  いずれのツールでも拒否されます (deny > allow)。',
    '- 読み取り専用 / append-only 権限モードでは書き込み/削除ツールは広告されません。',
  ].join('\n'),

  vault: [
    '# vault 初期セットアップ (vault_seed)',
    '',
    '`vault_seed` ツールは Loamium 同梱のサンプルファイルを vault へ投入します。',
    'POST /api/vault/seed と同一の SeedService を経由します (ADR-0016)。',
    '',
    '## 投入される内容',
    '',
    '- `system/commands/` — スマートコマンド定義 YAML (todo-add / log-memo / meeting-summary)',
    '- `templates/` — テンプレート Markdown (journal / 議事録 / 読書メモ)',
    '- `system/smart-folders/` — スマートフォルダ定義 YAML (recent / journal / todos / bookmarks)',
    '- `samples/` — 機能ガイド Markdown・サンプルデータ・画像 (samples/index.md 他)',
    '',
    '## vault_seed (サンプル投入, 書き込み)',
    '',
    '- 入力パラメータ:',
    '  - `force` — true なら既存ファイルを上書きする (既定 false: 既存はスキップ)。',
    '- 出力: `{ seeded, skipped, message }` — 投入ファイル数とスキップ数。',
    '- `force` 省略 (または false) の場合: 既存ファイルはスキップされ、上書きしません。',
    '  2 回実行してもファイルの内容は変わりません。',
    '- スキップ条件: vault 内に同名ファイルが既に存在する場合 (force=false のとき)。',
    '- 監査ログ: `op: "agent.vault_seed"` で `.loamium/audit.log` に記録されます。',
    '',
    '使用例:',
    '',
    '- 初回セットアップ: `vault_seed` に引数なし (または `force: false`) で投入。',
    '- サンプルをリセットしたい場合: `vault_seed` に `force: true` で全上書き。',
    '',
    '注意点:',
    '',
    '- `vault_seed` は write 権限 (vault_seed ケーパビリティ / full モード) でのみ利用できます。',
    '  読み取り専用・append-only では広告されません。',
    '- CLI からは `loamium init-samples` (または `--force`) で同じ操作が行えます。',
    '- 投入されるすべてのファイルはピュア Markdown または純 YAML です (独自記法なし)。',
  ].join('\n'),

  file: [
    '# 添付ファイルの作成・リネーム・削除 (書き込みツール)',
    '',
    '.md 以外の添付ファイル (画像・PDF・テキスト等) を操作する書き込みツール群です。',
    'いずれも REST と同一のサービス層 (file-service.ts) を経由し、パス正規化・監査ログを継承します。',
    'すべて file_write ケーパビリティで広告され、full 権限モードでのみ利用できます。',
    '(.md はノート API 側の管理対象です。ノートは note_create / note_edit / note_move を使ってください。)',
    '',
    '## file_write (作成/上書き, 書き込み)',
    '',
    '- 入力: `path` (vault 相対), `content` (テキスト), `encoding?` ("utf8" 既定 | "base64"),',
    '  `overwrite?` (既定 false)。',
    '- エージェントはテキストしか渡せません。**バイナリ (画像等) は base64 に変換して**',
    '  `content` に渡し、`encoding: "base64"` を指定します。',
    '- 既定では既存を上書きしません (overwrite:true のときだけ既存を置き換えます)。',
    '- サイズ上限 (LOAMIUM_MAX_UPLOAD。既定 50MB) を超える content はエラーになります。',
    '',
    '## file_move (リネーム/移動, 書き込み)',
    '',
    '- 入力: `from` (移動元 vault 相対パス), `to` (移動先 vault 相対パス)。',
    '- vault 全体の ![[旧名]] 埋め込みリンクを新パスへ**一括追従**します (曖昧リンクは触りません)。',
    '- 移動先が既に存在する場合はエラー (上書きしません)。from が存在しない場合もエラー。',
    '',
    '## file_delete (削除, 書き込み)',
    '',
    '- 入力: `path` (削除する vault 相対パス)。',
    '- **この操作は不可逆です** — ファイルを削除します。vault は Git 管理前提で、復旧は git 履歴に依存します。',
    '- 存在しない path はエラーにせず「削除対象なし」を返します (冪等)。',
    '',
    '共通の注意点:',
    '',
    '- vault 外への脱出 (`../`) / 隠しセグメント (`.loamium` 等) / 機密領域 (privacy deny) は',
    '  いずれのツールでも拒否されます (deny > allow)。file_move は from / to の両方を検証します。',
    '- .md への書き込み・リネームは拒否されます (ノート API へ誘導)。',
    '- 読み取り専用 / append-only 権限モードでは広告されません (full のみ)。',
  ].join('\n'),

  'task-fields': [
    '# タスク インラインフィールド (task_set_fields / ADR-0029)',
    '',
    'Loamium のタスクは Markdown チェックボックス行 (`- [ ] テキスト`) に',
    'Dataview 互換のインラインフィールド `[key:: value]` を付与して拡張します。',
    'チェックボックス文字 ([ ] / [x]) は done/not-done のみを表し、',
    'status / priority / due は常にインラインフィールドで保持します (ADR-0029)。',
    '',
    '## task_set_fields (タスクフィールド設定, 書き込み)',
    '',
    '- 入力パラメータ:',
    '  - `path` — vault 相対パス (既存ノート)',
    '  - `line` — 0-indexed 行番号 (task_query / dql_query の "line" フィールドと対応)',
    '  - `status?` — 設定する status 文字列。null でフィールドを削除。省略は変更なし',
    '  - `priority?` — 設定する priority 文字列。null でフィールドを削除。省略は変更なし',
    '  - `due?` — 設定する due 日付 (YYYY-MM-DD)。null でフィールドを削除。省略は変更なし',
    '- 出力: 成功テキスト、または失敗時はエラーテキスト',
    '- 制約: `note_edit` ケーパビリティが必要 (full モードでのみ広告)',
    '',
    '## 使用例',
    '',
    '```jsonc',
    '// status=progress に設定し、due を 2026-08-01 に設定する',
    '{ "path": "todos/sprint.md", "line": 5, "status": "progress", "due": "2026-08-01" }',
    '',
    '// priority フィールドを削除する (null = 削除)',
    '{ "path": "todos/sprint.md", "line": 5, "priority": null }',
    '',
    '// status のみ変更し、他は維持する (省略 = 変更なし)',
    '{ "path": "todos/sprint.md", "line": 5, "status": "done" }',
    '```',
    '',
    '## インラインフィールドの書式 (Dataview 互換)',
    '',
    '- フィールドは行末に `[key:: value]` の形式で付与されます',
    '- 例: `- [ ] タスクのテキスト [status:: progress] [due:: 2026-08-01]`',
    '- 同じキーが既存の場合は置き換え、なければ行末に追記、null なら削除します',
    '- インラインコード (`\`...\``) 内のフィールドは無視されます',
    '',
    '## タスクのクエリとの組み合わせ',
    '',
    '1. `dql_query` で `TASK WHERE status = "todo"` を実行してタスク一覧を取得',
    '2. 結果の `line` フィールドを `task_set_fields` の `line` に渡して更新',
    '3. 同じノートを再クエリして変更を確認',
    '',
    '## 注意点',
    '',
    '- 対象行がタスク行でない場合 (`- [ ]` / `- [x]` 以外) はエラー',
    '- 行番号はノートの編集により変化します。更新前に最新の line を取得してください',
    '- patchNote の一意性制約: 同一テキストの行が複数ある場合はエラー。',
    '  その場合は note_edit で直接テキスト置換を行ってください',
    '- 書き込みは監査ログ (`op: "agent.task_set_fields"`) に記録されます (ADR-0016)',
    '- 読み取り専用 / append-only 権限モードでは広告されません',
  ].join('\n'),

  current_note_context: [
    '# 現在開いている文書コンテキスト (Story 7)',
    '',
    'ユーザーがエディタでノートを開いた状態でメッセージを送ると、そのノートのパスが',
    'ターンのコンテキストとして自動的に注入されます。',
    '',
    '## 動作',
    '',
    '- メッセージ本文の先頭に `[現在開いているノート: <パス>]` が付与される。',
    '- これにより Agent は「この文書を要約して」「今開いているノートを編集して」等の',
    '  曖昧な指示を受けたとき、対象ノートを明示せずに操作できる。',
    '- ノートが開かれていない場合はコンテキスト注入なし (通常通り動作)。',
    '- vault 内パスとして安全に検証されている (../ 脱出は注入されない)。',
    '',
    '## 使用例',
    '',
    '- 「この文書を 3 行で要約して」→ Agent が開いているノートを read_note で読んで要約',
    '- 「タイトル見出しに今日の日付を追加して」→ Agent が現在ノートを参照して編集',
    '',
    '## 制約',
    '',
    '- コンテキスト注入はターン開始時の値を使用する。送信後のノート切り替えは反映されない。',
    '- system/ 配下や機密領域 (deny) のノートが開いていてもパスは注入されるが、',
    '  Agent のツールはサービス層の deny チェックで通常通り拒否される (ADR-0018)。',
    '- ケーパビリティ境界は変わらない。読み取りは read ケーパビリティ、',
    '  書き込みは対応する書き込みケーパビリティが必要 (ADR-0015)。',
  ].join('\n'),

  agent_default_preset: [
    '# Agent 新規セッションの既定権限 (Sfa11c0 / Story 5)',
    '',
    'Agent ページの権限ポップオーバー(盾アイコン)で、新規セッションを開始するときの',
    '初期権限を設定できます。プリセット (read-only / notes-rw / full) だけでなく、',
    '個別ケーパビリティを組み合わせた**カスタム集合**も既定として保存できます。',
    '',
    '## 設定場所',
    '',
    '- **Agent ページ**: セッションバーの盾アイコン → 権限ポップオーバー → プリセット選択 or',
    '  個別トグルで集合を作り → 「この権限を新規セッションの既定にする」ボタンで保存。',
    '  (全体設定 UI からは編集しません。Agent ページで完結します。)',
    '- **system/settings.yaml** のキー (agent 編集可):',
    '  - `agentDefaultCapabilities:` — カスタム集合 (ケーパビリティ名の配列)。優先。',
    '  - `agentDefaultPreset:` — プリセット名 (後方互換)。上記が無い場合に使う。',
    '',
    '## プリセット (ADR-0015 ケーパビリティプリセット。カスタムは任意に選択可)',
    '',
    '| プリセット | 含まれるケーパビリティ | 用途 |',
    '|---|---|---|',
    '| read-only | read のみ (既定) | 読み取り専用 |',
    '| notes-rw  | read, journal_append, note_create, note_edit | ノート読み書き |',
    '| full      | 全ケーパビリティ | フル操作 |',
    '',
    '## セキュリティ保証',
    '',
    '- 既定を `full` に設定しても、deny リスト (機密領域 ADR-0018) は常に有効です。',
    '- 自己昇格防止 (ADR-0026): agent は設定の変更ツールを持ちません。',
    '- サーバーの LOAMIUM_MODE によるクランプ (ADR-0015) は設定値に関わらず適用されます。',
    '  例: LOAMIUM_MODE=read-only なら full 設定でも実効権限は read のみになります。',
    '',
    '## 動作',
    '',
    '- 新規セッションを開始するとき、既定集合が選択権限 (selectedCaps) の初期値になります。',
    '- 解決順: agentDefaultCapabilities → agentDefaultPreset → read-only フォールバック。',
    '- セッション開始後に権限ポップオーバーから権限を変更することは引き続き可能です。',
    '- 既存セッションに切り替えた場合は設定値でなくそのセッションの実効権限が表示されます。',
    '',
    '## system/settings.yaml での直接設定例',
    '',
    '```yaml',
    '# system/settings.yaml',
    '# カスタム集合 (優先)',
    'agentDefaultCapabilities:',
    '  - read',
    '  - journal_append',
    '  - note_create',
    '# または プリセット (後方互換)',
    '# agentDefaultPreset: notes-rw',
    '```',
  ].join('\n'),
};

/** 利用可能トピックのソート済み一覧 (安定した出力のため)。 */
export function helpTopicNames(): string[] {
  return Object.keys(AGENT_HELP_TOPICS).sort();
}

/**
 * トピック指定を解決してガイド本文を返す。
 *
 * - topic が既知トピック (大文字小文字・前後空白は無視) ならその本文を返す。
 * - topic が未指定 (undefined/空文字) または未知トピックの場合は、
 *   エラーにせず利用可能トピック一覧の案内文字列を返す (AC-S10a31c-2-1)。
 */
export function resolveHelpTopic(topic?: string): string {
  const normalized = typeof topic === 'string' ? topic.trim().toLowerCase() : '';
  if (normalized && Object.prototype.hasOwnProperty.call(AGENT_HELP_TOPICS, normalized)) {
    const body = AGENT_HELP_TOPICS[normalized];
    if (body !== undefined) return body;
  }

  const names = helpTopicNames();
  const list = names.map((n) => `- ${n}`).join('\n');
  const header = normalized
    ? `不明なトピック "${topic ?? ''}" です。利用可能なトピック:`
    : '利用可能なトピック (topic を指定してください):';
  return `${header}\n${list}`;
}
